apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true" # 프로메테우스에게 이 파드에 있는 컨터에너로부터 데이터를 가져와야함을 알린다
        prometheus.io/path: /actuator/prometheus # 프로메테우스 메트릭을 제공하는 http 엔드포인트 지정
        prometheus.io/port: "9002" # 메트릭 엔드포인트 포트
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 13
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 8
            periodSeconds: 15
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]  # 쿠버네티스가 파드에 SIGTERM 신호를 보내기 전에 5초를 기다려 전체에 요청 전달 중지 명령을 할 수 있도록
          ports:
            - containerPort: 9002
              protocol: TCP
          env:
            - name: BVL_JVM_THREAD_COUNT
              value: "50"
          volumeMounts:
            - mountPath: /workspace/config
              name: order-config-volume
      volumes:
        - name: order-config-volume
          configMap:
            name: order-config
